accounts/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib.auth.views import PasswordResetCompleteView
from django.urls import path, re_path

from . import views
from .views import PasswordResetConfirmViews, PasswordResetDoneViews, PasswordResetViews

urlpatterns = [
    path("password_reset/",
         PasswordResetViews.as_view(),
         name="password_reset"),
    path(
        "password_reset/done/",
        PasswordResetDoneViews.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"^reset/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$",
        PasswordResetConfirmViews.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    re_path(r"^profile/$", views.view_profile, name="view_profile"),
    re_path(
        r"^changepassword/$", views.change_password, name="change_password"),
    re_path(r"^login/$", views.loginform, name="signin"),
    re_path(r"^logout/$", views.user_logout, name="signout"),
    path("signup/", views.signup, name="signup"),
    path("", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tgl/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.generic import RedirectView

from announcements.views import *
from main.views import *

from .sitemaps import StaticViewSitemap

sitemaps = {"static": StaticViewSitemap}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("account/", include("accounts.urls")),
    path("accounts/", include("accounts.urls")),
    path("payments/", include("payments.urls")),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="Sitemap"),
    path("", home, name="home"),
    path("make_groups/", group_make, name="make_groups"),
    path("about_game/<int:game_id>", view_games, name="about_game"),
    path("announcements/", view_annoucements, name="all_anouncements"),
    path(
        "announcements/<uuid:announcement_id>",
        view_annoucements_full,
        name="announcement_detail",
    ),
    path(
        "privacy_policy/",
        RedirectView.as_view(
            url="https://github.com/Tanzanite-lpu/tgl-2.0/wiki/Privacy-Policy"
        ),
        name="privacy_policy",
    ),
    path(
        "cookie_policy/",
        RedirectView.as_view(
            url="https://github.com/Tanzanite-lpu/tgl-2.0/wiki/Cookie-Policy"),
        name="cookie_policy",
    ),
    path(
        "tos/",
        RedirectView.as_view(
            url="https://github.com/Tanzanite-lpu/tgl-2.0/wiki/Terms-&-Conditions"
        ),
        name="tos",
    ),
    path(
        "refunds/",
        RedirectView.as_view(
            url="https://github.com/Tanzanite-lpu/tgl-2.0/wiki/Cancellation--&-Refund-Policy"
        ),
        name="refunds",
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import uuid

from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from main.models import GameGroup
from payments.models import Payments
from referral.models import Referral


def validate_zip(value):
    if not value.isdigit():
        raise ValidationError(
            _("%(value)s is not a valid zip code"),
            params={"value": value},
        )
    list_value = value.split(" ")
    str_value = "".join(list_value)
    return str_value


def validate_city(value):
    if len(value) < 2:
        raise ValidationError(
            _("%(value)s is not a valid city name"),
            params={"value": value},
        )


def validate_address(value):
    if len(value) <= 1 or value.isnumeric():
        raise ValidationError(
            _("%(value)s is not a valid address"),
            params={"value": value},
        )


def validate_phone(value):
    for i in str(value[1:]):
        if i.isspace():
            pass

        elif not i.strip(" ").isdigit():
            raise ValidationError(
                _(f"{value} is not a valid phone number"),
                params={"value": i},
            )
    if not value.strip(" ")[0] in "+":
        raise ValidationError(
            _(f"{value} is not a phone number, Please enter a no like +91 67xxxxxxxx"
              ),
            params={"value": value},
        )


class User(AbstractUser):
    gender = models.CharField(
        max_length=11,
        choices=(("M", "Male"), ("F", "Female"), ("O", "Others")),
        null=True,
    )
    phone = models.CharField(
        _("phone"),
        max_length=15,
        validators=[MinLengthValidator(10)],
        help_text=_("It should be +91 67xxx"),
    )
    address1 = models.TextField(_("address 1"), validators=[validate_address])
    address2 = models.TextField(_("address 2"),
                                validators=[validate_address],
                                blank=True,
                                null=True)
    city = models.CharField(_("city"),
                            max_length=500,
                            validators=[validate_city])
    state = models.CharField(_("state"), max_length=250)
    country = models.CharField(_("country"), max_length=250, null=True)
    unique_id = models.UUIDField(default=uuid.uuid4)
    zip_code = models.CharField(_("zip code"),
                                max_length=6,
                                validators=[validate_zip])
    university_name = models.CharField(_("University or College Name"),
                                       max_length=250)
    registration_no = models.CharField(
        _("Registration No"),
        validators=[MinLengthValidator(2)],
        null=True,
        blank=True,
        max_length=250,
        help_text=_("Your college issued ID (Optional)"),
    )
    orders = models.ManyToManyField(
        Payments,
        help_text=_("This is to be filled by computer"),
        blank=True,
    )
    referral_code = models.ForeignKey(Referral,
                                      on_delete=models.CASCADE,
                                      null=True,
                                      blank=True)

    def group_unique_id(self):
        for i in self.orders.all():
            if i.payment_status == "S":
                game_group = ""
                for j, i in enumerate(
                        GameGroup.objects.filter(payment_id=i).iterator()):
                    game_group += (
                        f"Game Group {j+1}: {i.group_unique_id} ; {i.game.name}\n"
                    )
                return game_group

    class Meta:
        unique_together = ("email", "registration_no")

accounts/views.py
import ast
import functools
import secrets
import string

from asgiref.sync import sync_to_async
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import (
    PasswordResetConfirmView,
    PasswordResetDoneView,
    PasswordResetView,
)
from django.contrib.sites.shortcuts import get_current_site
from django.db.models import Q
from django.http import HttpResponsePermanentRedirect
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.utils.translation import gettext_lazy as _
from post_office import mail
from post_office.models import EmailTemplate

from main.decorators import new_session_message
from main.tasks import mail_queue
from referral.models import Referral

from .forms import (
    EditProfileForm,
    LoginForm,
    PasswordChangeForms,
    PasswordReset,
    PasswordResetConfirmForm,
    SignupForm,
)
from .models import User
from .tokens import account_activation_token


# Create your views here.
class PasswordResetConfirmViews(PasswordResetConfirmView):
    mail_queue.delay()
    form_class = PasswordResetConfirmForm


class PasswordResetViews(PasswordResetView):
    html_email_template_name = "registration/password_reset_email.html"
    form_class = PasswordReset
    title = _("Password reset")
    description = _(
        "Password Reset for the existing account for the Tanzanite Gaming League 2.0"
    )

    @functools.lru_cache(maxsize=4)
    def form_valid(self, form):
        opts = {
            "use_https": self.request.is_secure(),
            "token_generator": self.token_generator,
            "from_email": settings.EMAIL_HOST_USER,
            "email_template_name": self.email_template_name,
            "subject_template_name": self.subject_template_name,
            "request": self.request,
            "html_email_template_name": self.html_email_template_name,
            "extra_email_context": self.extra_email_context,
        }
        form.save(**opts)
        return super().form_valid(form)


class PasswordResetDoneViews(PasswordResetDoneView):
    template_name = "registration/password_reset_done.html"
    title = _("Password reset sent")


@sync_to_async
@login_required
def view_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST,
                               instance=request.user,
                               admin=False)

        if form.is_valid():
            user = form.save(commit=False)
            referral = request.POST.get("referral_code")
            if len(referral) == 0 or referral in [None, ""]:
                user.referral_code = None
            else:
                if Referral.objects.filter(referral_code=referral).exists():
                    request.user.referral_code = Referral.objects.filter(
                        referral_code=referral).get()
                else:
                    messages.warning(
                        request,
                        f"<strong>{referral}</strong> Referral Code does not exists",
                    )

            messages.success(
                request,
                "Your <strong>Profile</strong> has been update successfully !")
            form.save(commit=True)
            return redirect(reverse("view_profile"))
        if not form.errors:
            messages.error(request,
                           "Please correct the errors mentioned below!")

    else:
        form = EditProfileForm(instance=request.user, admin=False)
    return render(
        request,
        "accounts/signup_and_different_template.html",
        {
            "form": form,
            "heading": "Update Profile",
            "title": "Update Profile",
            "view_profile": True,
            "no_display_messages": True,
            "referral": True,
        },
    )


@sync_to_async
@login_required
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForms(data=request.POST, user=request.user)

        if form.is_valid():
            messages.success(
                request,
                "Your <strong>password</strong> has been update successfully !"
            )
            form.save()
            update_session_auth_hash(request, form.user)
            return HttpResponsePermanentRedirect(reverse("change_password"))
        messages.error(request, "Please correct the errors mentioned below!")
    else:
        form = PasswordChangeForms(user=request.user)
    return render(
        request,
        "accounts/signup_and_different_template.html",
        {
            "form": form,
            "heading": "Change Password",
            "no_display_messages": True,
            "title": "Change Password",
        },
    )


@sync_to_async
@login_required
def user_logout(request):
    logout(request)
    messages.success(request, "You have been successfully logged out!")
    return HttpResponsePermanentRedirect(reverse("home"))


@sync_to_async
@new_session_message
def loginform(request):
    if request.method == "POST":
        form = LoginForm(request=request, data=request.POST)

        username_email = request.POST.get("username_email")
        user_obj = User.objects.filter(
            Q(username=username_email) | Q(email=username_email))
        if not user_obj.exists():
            messages.warning(request, "Please create an new account !")
            return redirect(reverse("signin"))
        if form.is_valid():
            username = user_obj.all()[0].username
            password = form.cleaned_data.get("password")
            try:
                next_url = ast.literal_eval(str(request.POST.get("next")))
            except:
                next_url = request.POST.get("next")

            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}")
                if bool(next_url):
                    return HttpResponsePermanentRedirect(next_url)
                return HttpResponsePermanentRedirect(reverse("home"))
            messages.error(request, "Invalid username or password.")
            return redirect(reverse("signin"))
        messages.error(request, "Details Invalid")
        return redirect(reverse("signin"))
    form = LoginForm()
    mail_queue.delay()
    return render(
        request,
        "login.html",
        {
            "title": "Login",
            "form": form,
            "next_url": request.GET.get("next")
        },
    )


@sync_to_async
@new_session_message
def signup(request):
    current_site = get_current_site(request)
    if request.method == "POST":
        form = SignupForm(request.POST)

        if form.is_valid():

            def generate_code(n: int = 7):
                return "".join(
                    secrets.choice(string.ascii_letters + string.digits +
                                   str(secrets.randbits(7)))
                    for i in range(n)).upper()

            username = generate_code()
            password = generate_code(10)
            data = form.cleaned_data
            data.update({
                "username": username,
                "password": password,
                "is_active": True,
                "address1": data.get("address"),
            })
            try:
                del data["address"]
            except:
                pass
            user = User.objects.create_user(**data)
            referral = request.POST.get("referral_code")
            if len(referral) == 0 or referral in [None, ""]:
                user.referral_code = None
            elif Referral.objects.filter(referral_code=referral).exists():
                user.referral_code = Referral.objects.filter(
                    referral_code=referral).get()
            else:
                messages.warning(
                    request,
                    f"<strong>{referral}</strong> Referral Code does not exists",
                )
            user.save()
            to_email = form.cleaned_data.get("email")
            ctx = {
                "user": user,
                "domain": current_site.domain,
                "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                "token": account_activation_token.make_token(user),
                "username": username,
                "password": password,
                "protocol": "https" if request.is_secure() else "http",
            }
            if not EmailTemplate.objects.filter(name="register_mail").exists():
                message = render_to_string("accounts/register_mail.html")
                mail_subject = "Thanks for Registering for TGL-2.0"
                EmailTemplate.objects.create(
                    name="register_mail",
                    description="Thank you E-Mail Template",
                    subject=mail_subject,
                    html_content=message,
                )
            mail.send(
                to_email,
                settings.EMAIL_HOST_USER,
                template="register_mail",
                context=ctx,
            )
            mail_queue.delay()
            messages.success(
                request,
                f"Account created, please see your mail {to_email} for the instructions on how to proceed further!, <br/> Check {to_email} , To get your <strong>username</username> and <strong>password</password>",
            )
            return redirect(reverse("make_order"))
        message_error_list = []
        if form.errors.as_data():
            for i in form.errors.as_data():

accounts/templates/accounts/signup_and_different_template.html
 {% extends "layout.html" %}{% load static %}{% load getfunc %}{% load compress %}{% block body %} {% compress css %}
<link rel="stylesheet" href="{% static 'css/signinstyle.css' %}"> {% endcompress %}
<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
<style>
    body {
        background-image: url('{% static "images/freefire.webp" %}');
    }
    
    label[for="id_gender"] {
        color: black;
    }
</style>

<!-- JavaScript Bundle with Popper -->
<div class="login-box container" style="margin-top: 5px; margin-bottom: 5px">
    <div class="back-box">
        <center>
            <div class="row">
                <h1 class="col">{{heading}}</h1>
            </div>
        </center>
        <!-- ==Flashed Message== -->
        {% if messages %} {% for message in messages %}
        <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %} role="alert">
            {{message|safe}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %} {% endif %} {% for error in form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{form.errors|get_val:error}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
        <!-- ==Ends== -->
        <div class="container">
            <form action="?" autocomplete="off" class="form-floating row needs-validation" method="POST">{% csrf_token %} {% for field in form %}
                <div data-aos="fade-down" class="textbox form-floating col-md-{% if forloop.counter == 1 or forloop.counter == 4 %}12{% else %}6{% endif %}">
                    {{ field }}{{ field.label_tag }}{% if field.help_text %}<br/><br/><span style="font-size: 15px;" class="help_text{{forloop.counter}}">{{ field.help_text }}</span> {% endif %} <br/><br/> {% for error in field.errors %}
                    <span style="font-size: 15px;" class="text-danger">
                        {{error}}
                    </span>{% endfor %}
                </div>
                {% endfor %}{% if referral %}
                <div class="textbox form-floating col-md-12" data-aos="zoom-in">
                    <input class="form-control" id="id_referral_code" maxlength="6" name="referral_code" value="{% if user.referral_code %}{{user.referral_code}}{% endif %}{% if referral_code %}{{referral_code}}{% endif %}" type="text" />
                    <label for="id_registration_no">Referral Code:</label>
                    <br/><br/>
                    <span style="font-size: 15px;">(Optional | Case Sensitive)</span> <br/><br/>
                </div>
                {% endif %}{% if view_profile %}
                <div data-aos="zoom-in" class="textbox form-floating col-md-10"><input class="form-control" disabled="true" id="id_unique_id" name="unique_id" type="text" value="{{user.unique_id}}" /><label for="id_unique_id">Unique id:</label></div>{% endif %} {% if display %}
                <div class="mb-3 form-check">
                    <input type="checkbox" class="form-check-input" id="aggrement" required>
                    <label class="form-check-label" for="aggrement">By registering yourself in TGL 2.0, you agree to our <a href="{% url 'tos' %}" target="_blank" title="Terms & Condition">Terms & Condition</a> and our <a href="{% url 'privacy_policy' %}" target="_blank" title="Privacy Policy">Privacy Policy</a></label>
                </div>
                {% endif %}
                <button data-aos="zoom-in-up" type="submit" class="sign_in_btn">{{heading}}</button>
            </form>
        </div>
        {% if display %}
        <a data-aos="zoom-in-up" href="{% url 'signin' %}"><button data-aos="zoom-in-up" type="submit" class="sign_up_btn">Login</button> </a>
        <a data-aos="zoom-in-up" href="{% url 'home' %}"><button data-aos="zoom-in-up" type="submit" class="back_btn">Home</button> </a> {% endif %}
    </div>
</div>
{% endblock %}